### ISSUE TITLE
Addon doesn't detect bundle permissions

### ISSUE THREAD

**Issue by Awakened-Redstone** [BentoBoxWorld/MagicCobblestoneGenerator#102]
#### Describe the bug

Setting the default group or a player a bundle permission doesn't limit the player/group to that bundle.

#### Steps to reproduce the behavior

1. Make 2 bundles with different generators
2. Set the permission for one of the bundes on the default group or yourself
3. Check the generators GUI

#### Expected behavior

The players should only be able to see and use the generators of the bundle their permission is set to.

#### Screenshots and videos (Optional)

https://user-images.githubusercontent.com/40528665/119350167-606ec600-bc75-11eb-8e4d-280896c3556c.mp4

##### Output of `/bbox version` (Mandatory)

```
Running PAPER 1.16.5.
BentoBox version: 1.16.1
Database: JSON
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, The End
Loaded Addons:
Biomes 1.14.0 (ENABLED)
BSkyBlock 1.14.4 (ENABLED)
Challenges 0.8.4 (ENABLED)
ControlPanel 1.13.0 (ENABLED)
DimensionalTrees 1.6.0 (ENABLED)
ExtraMobs 1.11.0.3 (ENABLED)
Greenhouses 1.5.2 (ENABLED)
IslandFly 1.8.1 (ENABLED)
Level 2.6.2 (ENABLED)
Limits 1.15.5 (ENABLED)
MagicCobblestoneGenerator 2.4.0-SNAPSHOT-b227 (ENABLED)
Upgrades 0.2.0-SNAPSHOT-b81 (ENABLED)
Visit 1.3.0 (ENABLED)
Warps 1.10.2 (ENABLED)
```

#### Plugins (Optional)

```
Plugins (42): AnotherDailyBonus, AuctionGUIPlus, AutoReplant, BentoBox, BuycraftX, ChestShop, CMI, CMILib, ColoredAnvils*, ColoredTags*, CombatLogX, Command4Bungee*, CoreProtect, CrateReloaded, DeathMessagesPrime, DeluxeMenus, EpicAnchors, EpicHoppers, EpicSpawners, Essentials, FeatherBoard*, GUIPlus, HolographicDisplays, LibsDisguises, LuckPerms, MessageFilter*, Multiverse-Core, MVdWPlaceholderAPI*, NexEngine, PlaceholderAPI, ProtocolLib, SellStick, ShopGUIPlus, Shopkeepers, SkBee, SkQuery, Skript, skript-placeholders*, spark, Vault, WorldEdit, WorldGuard
```
 
### Additional context (Optional)

Output of database export: https://paste.md-5.net/tujeceneba

**Comment by Awakened-Redstone** [comment]
Still an issue on 2.3.0

**Comment by BONNe** [comment]
So, the reason why your bundle permissions are not working is because of the wrong permission.

For some reason, your bundles `uniqueId` contains `&f` before their names. 

The reason why there is this color code is because of my bad generator creating implementation in-game. Sorry.

So your permissions for generators would be: `[gamemode].stone-generator.bundle.bskyblock_&fdefault`
Because of the color code, you even cannot see the correct permission via GUI, because of "color" parsing. 

I will implement code that will remove these color codes from the "uniqueId" assignment. 

You have 2 options:
- add &7 in your permissions
- in the exported database, fix unique Id's by removing &7 in them. And reimport your generators from the exported database file.


I am sorry for the late answer. Just bump with issues when you see that I ignore them... I am a human with a very bad memory and attention span.
