### ISSUE TITLE
magic cobblestone generator

### ISSUE THREAD

**Issue by threlief** [BentoBoxWorld/MagicCobblestoneGenerator#65]
#### Describe the bug
so i got the snapshot of the one u will release soon and its not doing much better we can unlock stuff now but even if the is level goes up to 20 k maybe once out of every 500 blocks do i see maybe iron or maybe coal and thats it it should be more often then that also how do u even get the points or whatever it is to unlock the generators
we not even getting diorite or other blocks we have the coal and iron ones unlocked and since we werent getting anything yet we cheated out is to 20k just to see what would happen and still nothing at all for over a hour only one iron and 1 coal
#### Steps to reproduce the behavior
idk how just we got this in the addon files with bskyblocks and its not working we even got the snapshot link from the discord support but its still not working

#### Expected behavior
to actually get blocks not just stone and cobble

##### Output of `/bbox version` (Mandatory)
Running PAPER 1.16.1.
BentoBox version: 1.14.2
Database: JSON
 Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, The End
Loaded Addons:
Biomes 1.7.0 (ENABLED)
BSkyBlock 1.14.0 (ENABLED)
Challenges 0.8.3 (ENABLED)
DimensionalTrees 1.6.0 (ENABLED)
 ExtraMobs 1.11.0.3 (ENABLED)
Greenhouses 1.0.0 (ENABLED)
slandFly 1.8.0 (ENABLED)
Level 2.3.2 (ENABLED)
Limits 1.14.0 (ENABLED)
MagicCobblestoneGenerator 2.1.0-SNAPSHOT-b152 (ENABLED)
 TwerkingForTrees 1.4.1 (ENABLED)
Warps 1.10.0 (ENABLED)

_______
```

#### Plugins (Optional)
<!-- Paste the `/plugins` output inside the code block below (remove the underscores). Do not provide an image. -->
```
_______
```
 
### Additional context (Optional)
<!-- Any additional information you'd like to provide us. -->
<!-- Please type below this line. -->
even the nether one dont work just in general the generator is not working as it should like it did in the 1,15,2 version

**Comment by BONNe** [comment]
Since 2.0 version users can choose which generator to activate. If users do not do anything, then only default generators will be active. 
It is done so we could implement #50 and #16. As well as allow to choose different results per each generator. 

In bskyblock, users must execute `/is generator` command and it will open view with all available generators.
![active-generators](https://user-images.githubusercontent.com/1344358/87856400-96417080-c927-11ea-86e8-29290cec8cbd.png)

When hovering on the generator tier, it should show tooltips about possible actions at the bottom of the lore.

And to buy a generator, if you have Vault and plugin that have an Economy (money) system, you need to right-click on a generator and then hover over a gold block.

![purchase](https://user-images.githubusercontent.com/1344358/87856483-2bdd0000-c928-11ea-8833-2d39080d646c.png)

**Comment by threlief** [comment]
already aware  of that we did buy and activate the coal ore and iron ore one but we are not getting coal or iron

**Comment by BONNe** [comment]
well,
I enable iron generator and the third block was iron ore....
![iron](https://user-images.githubusercontent.com/1344358/87856894-f2f25a80-c92a-11ea-901a-0ab150ff4eed.jpg)

Please check if the iron generator is enabled and that in a generator you have any chance to get iron ore, if you have customized it.

**Comment by threlief** [comment]
i havent changed any of the config and we changed to only have one thing active and still getting nothing but half chest cobble and one piece iron ore and we have only the diamond one active so what else could we possibly be doing wrong ?

**Comment by threlief** [comment]
ok so it seems the generator has to be in the grass we cannot make a big above ground one?

**Comment by threlief** [comment]
ok we figured it out apparently yalls new system requires the lava to be on the opposite side of water cannot go on top anymore

**Comment by BONNe** [comment]
Well, that is a stone generator...

Since 1.16 in minecraft exist 3 generators:
1- cobblestone -> when water touches lava
2- stone -> when lava flows over water
3- basalt -> when lava meets blue ice

Each generator can be configured to work only with one of the generator type. Default Iron Generator works only with Cobblestone generators.
