### ISSUE TITLE
Edit and make custom menus

### ISSUE THREAD

**Issue by Sushirod** [BentoBoxWorld/MagicCobblestoneGenerator#78]
#### Is your feature request related to a problem?
No, just to be more editable

#### Describe the solution you'd like us to implement.
You could add a menu config.yml where we can edit the position, name and lore, custom menu, size of the menu (up to 54) 

#### Describe alternatives you've considered.
- Do a menu.yml a) for the first menu where is listed all the generators and a file for the specifications menu
- Make more placeholders and add command buy of generators so we can create our custom menus using other plugin

### Additional context
It will be awesome 👍

**Comment by BONNe** [comment]
Some of the things you can already do:

1) Name is taken from the "name" field in the template and stored in the database. 
2) Lore is taken from the "description" field in the template and stored in the database. Also, some parts of the lore are added from the locale part, like requirements.

Menu size is based on element count. I am not keen to implement any custom "index" that would allow the specifying position of a generator, because it will be harder to add all generators in GUI if the user is **** and use the same number everywhere. 

The same is with the custom menu... It is not hard to implement, but as all generators are created dynamically, it is much easier to use element order based on priority/name, instead of guessing which menu item the user wanted in a specific position.

About placeholders:
- please use separate requests about the placeholder you want, and what it should return.

About commands:
- I will add a command to buy a generator.

**Comment by BONNe** [comment]
I added the buy command.
